#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/7/20
# @Author  : RoyYoung

"""atp文件开头的注释部分"""


class Info(object):

    def __init__(self):
        self.list = []

    def append(self, str):
        self.list.append(str)

    '''
    示例输出:
    C --------------------------------------------------------
    C Generated by ATPDRAW  七月, 星期五 20, 2018
    C A Bonneville Power Administration program
    C Programmed by H. K. H鴌dalen at SEfAS - NORWAY 1994-2002
    C --------------------------------------------------------
    $DUMMY, XYZ000
    '''

    def generate(self):
        str = ''
        for i in self.list:
            str += i + '\n'

        return str
