# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ATP_Helper.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 876)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_19 = QtWidgets.QLabel(self.centralWidget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.set_runATP = QtWidgets.QPushButton(self.widget)
        self.set_runATP.setObjectName("set_runATP")
        self.gridLayout_3.addWidget(self.set_runATP, 0, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 2, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 6, 1, 1)
        self.total_time = QtWidgets.QLineEdit(self.widget)
        self.total_time.setObjectName("total_time")
        self.gridLayout_3.addWidget(self.total_time, 2, 0, 1, 1)
        self.save_pro_btn = QtWidgets.QPushButton(self.widget)
        self.save_pro_btn.setObjectName("save_pro_btn")
        self.gridLayout_3.addWidget(self.save_pro_btn, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_3.addWidget(self.lineEdit_5)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 2, 3, 1, 1)
        self.time_offset = QtWidgets.QLineEdit(self.widget)
        self.time_offset.setObjectName("time_offset")
        self.gridLayout_3.addWidget(self.time_offset, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 2, 2, 1, 1)
        self.load_adp_btn = QtWidgets.QPushButton(self.widget)
        self.load_adp_btn.setObjectName("load_adp_btn")
        self.gridLayout_3.addWidget(self.load_adp_btn, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 4, 1, 1)
        self.atp_run = QtWidgets.QPushButton(self.widget)
        self.atp_run.setObjectName("atp_run")
        self.gridLayout_3.addWidget(self.atp_run, 0, 6, 1, 1)
        self.atp_update = QtWidgets.QPushButton(self.widget)
        self.atp_update.setObjectName("atp_update")
        self.gridLayout_3.addWidget(self.atp_update, 0, 5, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.label_27 = QtWidgets.QLabel(self.widget)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_3.addWidget(self.label_27)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_28 = QtWidgets.QLabel(self.widget)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 0, 0, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_8.addWidget(self.lineEdit_17, 1, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_8.addWidget(self.pushButton_5, 1, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.widget)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 0, 2, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_8.addWidget(self.lineEdit_16, 1, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.widget)
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 0, 3, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_8.addWidget(self.radioButton, 1, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.widget)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_8)
        self.label_32 = QtWidgets.QLabel(self.widget)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_3.addWidget(self.label_32)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_36 = QtWidgets.QLabel(self.widget)
        self.label_36.setObjectName("label_36")
        self.gridLayout_9.addWidget(self.label_36, 0, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.widget)
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.gridLayout_9.addWidget(self.label_39, 0, 3, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.widget)
        self.label_38.setObjectName("label_38")
        self.gridLayout_9.addWidget(self.label_38, 0, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.widget)
        self.label_37.setObjectName("label_37")
        self.gridLayout_9.addWidget(self.label_37, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_9.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_9.addWidget(self.radioButton_2, 1, 3, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_9.addWidget(self.lineEdit_18, 1, 1, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_9.addWidget(self.lineEdit_19, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_9)
        self.label_33 = QtWidgets.QLabel(self.widget)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_3.addWidget(self.label_33)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_40 = QtWidgets.QLabel(self.widget)
        self.label_40.setObjectName("label_40")
        self.gridLayout_10.addWidget(self.label_40, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_10.addWidget(self.pushButton_7, 1, 2, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_10.addWidget(self.radioButton_3, 1, 3, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.widget)
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.gridLayout_10.addWidget(self.label_43, 0, 3, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.widget)
        self.label_42.setObjectName("label_42")
        self.gridLayout_10.addWidget(self.label_42, 0, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.widget)
        self.label_41.setObjectName("label_41")
        self.gridLayout_10.addWidget(self.label_41, 0, 1, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_10.addWidget(self.lineEdit_21, 1, 1, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_10.addWidget(self.lineEdit_20, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem2, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_10)
        self.label_34 = QtWidgets.QLabel(self.widget)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_3.addWidget(self.label_34)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_11.addWidget(self.lineEdit_22, 1, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.widget)
        self.label_45.setObjectName("label_45")
        self.gridLayout_11.addWidget(self.label_45, 0, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.widget)
        self.label_46.setObjectName("label_46")
        self.gridLayout_11.addWidget(self.label_46, 0, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_11.addWidget(self.pushButton_8, 1, 2, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_11.addWidget(self.lineEdit_23, 1, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.widget)
        self.label_44.setObjectName("label_44")
        self.gridLayout_11.addWidget(self.label_44, 0, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_11.addWidget(self.radioButton_4, 1, 3, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.widget)
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.gridLayout_11.addWidget(self.label_47, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_11)
        self.label_35 = QtWidgets.QLabel(self.widget)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_3.addWidget(self.label_35)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_48 = QtWidgets.QLabel(self.widget)
        self.label_48.setObjectName("label_48")
        self.gridLayout_12.addWidget(self.label_48, 0, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.widget)
        self.label_49.setObjectName("label_49")
        self.gridLayout_12.addWidget(self.label_49, 0, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.widget)
        self.label_50.setObjectName("label_50")
        self.gridLayout_12.addWidget(self.label_50, 0, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.widget)
        self.label_51.setText("")
        self.label_51.setObjectName("label_51")
        self.gridLayout_12.addWidget(self.label_51, 0, 3, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_12.addWidget(self.lineEdit_24, 1, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_12.addWidget(self.radioButton_5, 1, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_12.addWidget(self.pushButton_9, 1, 2, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_12.addWidget(self.lineEdit_25, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem4, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_12)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 627, 471))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_14.setMinimumSize(QtCore.QSize(0, 0))
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.switch_add_list = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.switch_add_list.setObjectName("switch_add_list")
        self.gridLayout.addWidget(self.switch_add_list, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.switch_model_name = QtWidgets.QLineEdit(self.tab_2)
        self.switch_model_name.setText("")
        self.switch_model_name.setObjectName("switch_model_name")
        self.horizontalLayout_4.addWidget(self.switch_model_name)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.switch_model_list = QtWidgets.QListWidget(self.tab_2)
        self.switch_model_list.setObjectName("switch_model_list")
        self.horizontalLayout_5.addWidget(self.switch_model_list)
        self.switch_model_info = QtWidgets.QTextEdit(self.tab_2)
        self.switch_model_info.setEnabled(True)
        self.switch_model_info.setReadOnly(True)
        self.switch_model_info.setObjectName("switch_model_info")
        self.horizontalLayout_5.addWidget(self.switch_model_info)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.switch_model_apply = QtWidgets.QPushButton(self.tab_2)
        self.switch_model_apply.setObjectName("switch_model_apply")
        self.horizontalLayout.addWidget(self.switch_model_apply)
        self.switch_model_save = QtWidgets.QPushButton(self.tab_2)
        self.switch_model_save.setObjectName("switch_model_save")
        self.horizontalLayout.addWidget(self.switch_model_save)
        self.switch_model_del = QtWidgets.QPushButton(self.tab_2)
        self.switch_model_del.setObjectName("switch_model_del")
        self.horizontalLayout.addWidget(self.switch_model_del)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 629, 471))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem7, 3, 1, 1, 1)
        self.cm_resist = QtWidgets.QComboBox(self.scrollAreaWidgetContents_5)
        self.cm_resist.setObjectName("cm_resist")
        self.gridLayout_19.addWidget(self.cm_resist, 2, 0, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_73.setObjectName("label_73")
        self.gridLayout_19.addWidget(self.label_73, 1, 0, 1, 1)
        self.resist_arg_set = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.resist_arg_set.setObjectName("resist_arg_set")
        self.gridLayout_19.addWidget(self.resist_arg_set, 2, 1, 1, 1)
        self.resist_arg_del = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.resist_arg_del.setObjectName("resist_arg_del")
        self.gridLayout_19.addWidget(self.resist_arg_del, 2, 2, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_72.setObjectName("label_72")
        self.gridLayout_19.addWidget(self.label_72, 0, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.resist_add_list = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.resist_add_list.setObjectName("resist_add_list")
        self.gridLayout_20.addWidget(self.resist_add_list, 1, 0, 1, 1)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_8.addWidget(self.scrollArea_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_78 = QtWidgets.QLabel(self.tab_3)
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_7.addWidget(self.label_78)
        self.resist_model_name = QtWidgets.QLineEdit(self.tab_3)
        self.resist_model_name.setText("")
        self.resist_model_name.setObjectName("resist_model_name")
        self.horizontalLayout_7.addWidget(self.resist_model_name)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_80 = QtWidgets.QLabel(self.tab_3)
        self.label_80.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_80.setObjectName("label_80")
        self.horizontalLayout_8.addWidget(self.label_80)
        self.resist_model_list = QtWidgets.QListWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resist_model_list.sizePolicy().hasHeightForWidth())
        self.resist_model_list.setSizePolicy(sizePolicy)
        self.resist_model_list.setObjectName("resist_model_list")
        self.horizontalLayout_8.addWidget(self.resist_model_list)
        self.resist_model_info = QtWidgets.QTextEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resist_model_info.sizePolicy().hasHeightForWidth())
        self.resist_model_info.setSizePolicy(sizePolicy)
        self.resist_model_info.setReadOnly(True)
        self.resist_model_info.setObjectName("resist_model_info")
        self.horizontalLayout_8.addWidget(self.resist_model_info)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.resist_model_apply = QtWidgets.QPushButton(self.tab_3)
        self.resist_model_apply.setObjectName("resist_model_apply")
        self.horizontalLayout_6.addWidget(self.resist_model_apply)
        self.resist_model_save = QtWidgets.QPushButton(self.tab_3)
        self.resist_model_save.setObjectName("resist_model_save")
        self.horizontalLayout_6.addWidget(self.resist_model_save)
        self.resist_model_del = QtWidgets.QPushButton(self.tab_3)
        self.resist_model_del.setObjectName("resist_model_del")
        self.horizontalLayout_6.addWidget(self.resist_model_del)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_7.sizePolicy().hasHeightForWidth())
        self.scrollArea_7.setSizePolicy(sizePolicy)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 627, 471))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_8)
        self.gridLayout_21.setObjectName("gridLayout_21")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem9, 3, 0, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.cap_arg_set = QtWidgets.QPushButton(self.scrollAreaWidgetContents_8)
        self.cap_arg_set.setObjectName("cap_arg_set")
        self.gridLayout_22.addWidget(self.cap_arg_set, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        self.label_17.setObjectName("label_17")
        self.gridLayout_22.addWidget(self.label_17, 0, 0, 1, 1)
        self.cap_arg_del = QtWidgets.QPushButton(self.scrollAreaWidgetContents_8)
        self.cap_arg_del.setObjectName("cap_arg_del")
        self.gridLayout_22.addWidget(self.cap_arg_del, 1, 2, 1, 1)
        self.cm_cap = QtWidgets.QComboBox(self.scrollAreaWidgetContents_8)
        self.cm_cap.setObjectName("cm_cap")
        self.gridLayout_22.addWidget(self.cm_cap, 1, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_22, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_16.setObjectName("label_16")
        self.gridLayout_21.addWidget(self.label_16, 1, 0, 1, 1)
        self.cap_add_list = QtWidgets.QPushButton(self.scrollAreaWidgetContents_8)
        self.cap_add_list.setObjectName("cap_add_list")
        self.gridLayout_21.addWidget(self.cap_add_list, 4, 0, 1, 1)
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_8)
        self.verticalLayout_15.addWidget(self.scrollArea_7)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_60 = QtWidgets.QLabel(self.tab_4)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_12.addWidget(self.label_60)
        self.cap_model_name = QtWidgets.QLineEdit(self.tab_4)
        self.cap_model_name.setText("")
        self.cap_model_name.setObjectName("cap_model_name")
        self.horizontalLayout_12.addWidget(self.cap_model_name)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_61 = QtWidgets.QLabel(self.tab_4)
        self.label_61.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_13.addWidget(self.label_61)
        self.cap_model_list = QtWidgets.QListWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cap_model_list.sizePolicy().hasHeightForWidth())
        self.cap_model_list.setSizePolicy(sizePolicy)
        self.cap_model_list.setObjectName("cap_model_list")
        self.horizontalLayout_13.addWidget(self.cap_model_list)
        self.cap_model_info = QtWidgets.QTextEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cap_model_info.sizePolicy().hasHeightForWidth())
        self.cap_model_info.setSizePolicy(sizePolicy)
        self.cap_model_info.setReadOnly(True)
        self.cap_model_info.setObjectName("cap_model_info")
        self.horizontalLayout_13.addWidget(self.cap_model_info)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem10)
        self.cap_model_apply = QtWidgets.QPushButton(self.tab_4)
        self.cap_model_apply.setObjectName("cap_model_apply")
        self.horizontalLayout_14.addWidget(self.cap_model_apply)
        self.cap_model_save = QtWidgets.QPushButton(self.tab_4)
        self.cap_model_save.setObjectName("cap_model_save")
        self.horizontalLayout_14.addWidget(self.cap_model_save)
        self.cap_model_del = QtWidgets.QPushButton(self.tab_4)
        self.cap_model_del.setObjectName("cap_model_del")
        self.horizontalLayout_14.addWidget(self.cap_model_del)
        self.verticalLayout_15.addLayout(self.horizontalLayout_14)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_6.sizePolicy().hasHeightForWidth())
        self.scrollArea_6.setSizePolicy(sizePolicy)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 627, 471))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_7)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem11, 2, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.source_arg_set = QtWidgets.QPushButton(self.scrollAreaWidgetContents_7)
        self.source_arg_set.setObjectName("source_arg_set")
        self.gridLayout_13.addWidget(self.source_arg_set, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_13.setObjectName("label_13")
        self.gridLayout_13.addWidget(self.label_13, 0, 0, 1, 1)
        self.source_le_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_le_1.sizePolicy().hasHeightForWidth())
        self.source_le_1.setSizePolicy(sizePolicy)
        self.source_le_1.setObjectName("source_le_1")
        self.gridLayout_13.addWidget(self.source_le_1, 1, 1, 1, 1)
        self.source_arg_del = QtWidgets.QPushButton(self.scrollAreaWidgetContents_7)
        self.source_arg_del.setObjectName("source_arg_del")
        self.gridLayout_13.addWidget(self.source_arg_del, 1, 3, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_54.setObjectName("label_54")
        self.gridLayout_13.addWidget(self.label_54, 0, 1, 1, 1)
        self.cm_source = QtWidgets.QComboBox(self.scrollAreaWidgetContents_7)
        self.cm_source.setObjectName("cm_source")
        self.gridLayout_13.addWidget(self.cm_source, 1, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_13, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.gridLayout_15.addWidget(self.label_4, 0, 0, 1, 1)
        self.source_add_list = QtWidgets.QPushButton(self.scrollAreaWidgetContents_7)
        self.source_add_list.setObjectName("source_add_list")
        self.gridLayout_15.addWidget(self.source_add_list, 3, 0, 1, 1)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_13.addWidget(self.scrollArea_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_55 = QtWidgets.QLabel(self.tab)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_9.addWidget(self.label_55)
        self.source_model_name = QtWidgets.QLineEdit(self.tab)
        self.source_model_name.setText("")
        self.source_model_name.setObjectName("source_model_name")
        self.horizontalLayout_9.addWidget(self.source_model_name)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_58 = QtWidgets.QLabel(self.tab)
        self.label_58.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_10.addWidget(self.label_58)
        self.source_model_list = QtWidgets.QListWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_model_list.sizePolicy().hasHeightForWidth())
        self.source_model_list.setSizePolicy(sizePolicy)
        self.source_model_list.setObjectName("source_model_list")
        self.horizontalLayout_10.addWidget(self.source_model_list)
        self.source_model_info = QtWidgets.QTextEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_model_info.sizePolicy().hasHeightForWidth())
        self.source_model_info.setSizePolicy(sizePolicy)
        self.source_model_info.setReadOnly(True)
        self.source_model_info.setObjectName("source_model_info")
        self.horizontalLayout_10.addWidget(self.source_model_info)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.source_model_apply = QtWidgets.QPushButton(self.tab)
        self.source_model_apply.setObjectName("source_model_apply")
        self.horizontalLayout_11.addWidget(self.source_model_apply)
        self.source_model_save = QtWidgets.QPushButton(self.tab)
        self.source_model_save.setObjectName("source_model_save")
        self.horizontalLayout_11.addWidget(self.source_model_save)
        self.source_model_del = QtWidgets.QPushButton(self.tab)
        self.source_model_del.setObjectName("source_model_del")
        self.horizontalLayout_11.addWidget(self.source_model_del)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_52 = QtWidgets.QLabel(self.tab_7)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_9.addWidget(self.label_52)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_53 = QtWidgets.QLabel(self.tab_7)
        self.label_53.setObjectName("label_53")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.result_pro_name_le = QtWidgets.QLineEdit(self.tab_7)
        self.result_pro_name_le.setObjectName("result_pro_name_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.result_pro_name_le)
        self.label_64 = QtWidgets.QLabel(self.tab_7)
        self.label_64.setObjectName("label_64")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_64)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab_7)
        self.scrollArea_4.setEnabled(True)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 558, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_4.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_4.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.result_tips_gl = QtWidgets.QGridLayout()
        self.result_tips_gl.setObjectName("result_tips_gl")
        self.gridLayout_16.addLayout(self.result_tips_gl, 0, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.scrollArea_4)
        self.result_all_tips_rB = QtWidgets.QRadioButton(self.tab_7)
        self.result_all_tips_rB.setChecked(False)
        self.result_all_tips_rB.setObjectName("result_all_tips_rB")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.result_all_tips_rB)
        self.label_56 = QtWidgets.QLabel(self.tab_7)
        self.label_56.setObjectName("label_56")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.result_max_cb = QtWidgets.QCheckBox(self.tab_7)
        self.result_max_cb.setChecked(True)
        self.result_max_cb.setObjectName("result_max_cb")
        self.gridLayout_14.addWidget(self.result_max_cb, 0, 0, 1, 1)
        self.result_min_cb = QtWidgets.QCheckBox(self.tab_7)
        self.result_min_cb.setObjectName("result_min_cb")
        self.gridLayout_14.addWidget(self.result_min_cb, 0, 1, 1, 1)
        self.result_average_cb = QtWidgets.QCheckBox(self.tab_7)
        self.result_average_cb.setObjectName("result_average_cb")
        self.gridLayout_14.addWidget(self.result_average_cb, 0, 2, 1, 1)
        self.result_all_cb = QtWidgets.QCheckBox(self.tab_7)
        self.result_all_cb.setObjectName("result_all_cb")
        self.gridLayout_14.addWidget(self.result_all_cb, 0, 3, 1, 1)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.gridLayout_14)
        self.label_2 = QtWidgets.QLabel(self.tab_7)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.result_start_time = QtWidgets.QLineEdit(self.tab_7)
        self.result_start_time.setObjectName("result_start_time")
        self.horizontalLayout_15.addWidget(self.result_start_time)
        self.label_18 = QtWidgets.QLabel(self.tab_7)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_15.addWidget(self.label_18)
        self.result_end_time = QtWidgets.QLineEdit(self.tab_7)
        self.result_end_time.setObjectName("result_end_time")
        self.horizontalLayout_15.addWidget(self.result_end_time)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_15)
        self.verticalLayout_9.addLayout(self.formLayout)
        self.label_57 = QtWidgets.QLabel(self.tab_7)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_9.addWidget(self.label_57)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_71 = QtWidgets.QLabel(self.tab_7)
        self.label_71.setObjectName("label_71")
        self.gridLayout_18.addWidget(self.label_71, 0, 0, 1, 1)
        self.result_report_pic_cb = QtWidgets.QCheckBox(self.tab_7)
        self.result_report_pic_cb.setObjectName("result_report_pic_cb")
        self.gridLayout_18.addWidget(self.result_report_pic_cb, 1, 2, 1, 1)
        self.result_report_table_cb = QtWidgets.QCheckBox(self.tab_7)
        self.result_report_table_cb.setObjectName("result_report_table_cb")
        self.gridLayout_18.addWidget(self.result_report_table_cb, 1, 1, 1, 1)
        self.result_report_brief_cb = QtWidgets.QCheckBox(self.tab_7)
        self.result_report_brief_cb.setObjectName("result_report_brief_cb")
        self.gridLayout_18.addWidget(self.result_report_brief_cb, 1, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_18.addWidget(self.pushButton_11, 2, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_18.addWidget(self.pushButton_12, 2, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_18)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem13)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.radioButton_7 = QtWidgets.QRadioButton(self.tab_8)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_11.addWidget(self.radioButton_7)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem14, 3, 0, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.tab_8)
        self.label_66.setObjectName("label_66")
        self.gridLayout_17.addWidget(self.label_66, 1, 0, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_8)
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_17.addWidget(self.comboBox_8, 2, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.tab_8)
        self.label_65.setObjectName("label_65")
        self.gridLayout_17.addWidget(self.label_65, 0, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem15, 1, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_17)
        self.radioButton_8 = QtWidgets.QRadioButton(self.tab_8)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_11.addWidget(self.radioButton_8)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_67 = QtWidgets.QLabel(self.tab_8)
        self.label_67.setObjectName("label_67")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_67)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_28)
        self.label_68 = QtWidgets.QLabel(self.tab_8)
        self.label_68.setObjectName("label_68")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_68)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_29)
        self.label_69 = QtWidgets.QLabel(self.tab_8)
        self.label_69.setObjectName("label_69")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_69)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_30)
        self.label_70 = QtWidgets.QLabel(self.tab_8)
        self.label_70.setObjectName("label_70")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_70)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_10.setObjectName("pushButton_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_10)
        self.verticalLayout_11.addLayout(self.formLayout_2)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem16)
        self.tabWidget.addTab(self.tab_8, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.default_btn = QtWidgets.QPushButton(self.centralWidget)
        self.default_btn.setObjectName("default_btn")
        self.horizontalLayout_2.addWidget(self.default_btn)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem17)
        self.btn_run = QtWidgets.QPushButton(self.centralWidget)
        self.btn_run.setObjectName("btn_run")
        self.horizontalLayout_2.addWidget(self.btn_run)
        self.cancel_btn = QtWidgets.QPushButton(self.centralWidget)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.set_runATP.setText(_translate("MainWindow", "设置脚本路劲"))
        self.comboBox.setItemText(0, _translate("MainWindow", "True"))
        self.comboBox.setItemText(1, _translate("MainWindow", "False"))
        self.label_6.setText(_translate("MainWindow", "仿真次数"))
        self.label_9.setText(_translate("MainWindow", "绝对值"))
        self.save_pro_btn.setText(_translate("MainWindow", "保存项目"))
        self.label_7.setText(_translate("MainWindow", "时间偏移量"))
        self.label_10.setText(_translate("MainWindow", "波形提取时间"))
        self.label_8.setText(_translate("MainWindow", "重复结果%"))
        self.load_adp_btn.setText(_translate("MainWindow", "加载项目"))
        self.label_11.setText(_translate("MainWindow", "-"))
        self.atp_run.setText(_translate("MainWindow", "运行atp"))
        self.atp_update.setText(_translate("MainWindow", "更新atp"))
        self.label_27.setText(_translate("MainWindow", "开关信息"))
        self.label_28.setText(_translate("MainWindow", "是否修改"))
        self.pushButton_5.setText(_translate("MainWindow", "点击查看"))
        self.label_30.setText(_translate("MainWindow", "修改详情"))
        self.radioButton.setText(_translate("MainWindow", "禁用"))
        self.label_29.setText(_translate("MainWindow", "修改结果"))
        self.label_32.setText(_translate("MainWindow", "电阻信息"))
        self.label_36.setText(_translate("MainWindow", "是否修改"))
        self.label_38.setText(_translate("MainWindow", "修改详情"))
        self.label_37.setText(_translate("MainWindow", "修改结果"))
        self.pushButton_6.setText(_translate("MainWindow", "点击查看"))
        self.radioButton_2.setText(_translate("MainWindow", "禁用"))
        self.label_33.setText(_translate("MainWindow", "电容信息"))
        self.label_40.setText(_translate("MainWindow", "是否修改"))
        self.pushButton_7.setText(_translate("MainWindow", "点击查看"))
        self.radioButton_3.setText(_translate("MainWindow", "禁用"))
        self.label_42.setText(_translate("MainWindow", "修改详情"))
        self.label_41.setText(_translate("MainWindow", "修改结果"))
        self.label_34.setText(_translate("MainWindow", "线路信息"))
        self.label_45.setText(_translate("MainWindow", "修改结果"))
        self.label_46.setText(_translate("MainWindow", "修改详情"))
        self.pushButton_8.setText(_translate("MainWindow", "点击查看"))
        self.label_44.setText(_translate("MainWindow", "是否修改"))
        self.radioButton_4.setText(_translate("MainWindow", "禁用"))
        self.label_35.setText(_translate("MainWindow", "雷电元件信息"))
        self.label_48.setText(_translate("MainWindow", "是否修改"))
        self.label_49.setText(_translate("MainWindow", "修改结果"))
        self.label_50.setText(_translate("MainWindow", "修改详情"))
        self.radioButton_5.setText(_translate("MainWindow", "禁用"))
        self.pushButton_9.setText(_translate("MainWindow", "点击查看"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "总信息"))
        self.label.setText(_translate("MainWindow", "左右节点"))
        self.label_14.setText(_translate("MainWindow", "运行模式设置"))
        self.switch_add_list.setText(_translate("MainWindow", "添加"))
        self.label_12.setText(_translate("MainWindow", "模式名称"))
        self.label_15.setText(_translate("MainWindow", "模式信息"))
        self.switch_model_apply.setText(_translate("MainWindow", "应用"))
        self.switch_model_save.setText(_translate("MainWindow", "保存"))
        self.switch_model_del.setText(_translate("MainWindow", "删除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "开关"))
        self.label_73.setText(_translate("MainWindow", "左右节点"))
        self.resist_arg_set.setText(_translate("MainWindow", "参数设置"))
        self.resist_arg_del.setText(_translate("MainWindow", "移除"))
        self.label_72.setText(_translate("MainWindow", "运行模式设置"))
        self.resist_add_list.setText(_translate("MainWindow", "添加"))
        self.label_78.setText(_translate("MainWindow", "模式名称"))
        self.label_80.setText(_translate("MainWindow", "模式信息"))
        self.resist_model_info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.resist_model_apply.setText(_translate("MainWindow", "应用"))
        self.resist_model_save.setText(_translate("MainWindow", "保存"))
        self.resist_model_del.setText(_translate("MainWindow", "删除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "电阻"))
        self.cap_arg_set.setText(_translate("MainWindow", "参数设置"))
        self.label_17.setText(_translate("MainWindow", "左右节点"))
        self.cap_arg_del.setText(_translate("MainWindow", "移除"))
        self.label_16.setText(_translate("MainWindow", "运行模式设置"))
        self.cap_add_list.setText(_translate("MainWindow", "添加"))
        self.label_60.setText(_translate("MainWindow", "模式名称"))
        self.label_61.setText(_translate("MainWindow", "模式信息"))
        self.cap_model_apply.setText(_translate("MainWindow", "应用"))
        self.cap_model_save.setText(_translate("MainWindow", "保存"))
        self.cap_model_del.setText(_translate("MainWindow", "删除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "电容"))
        self.source_arg_set.setText(_translate("MainWindow", "参数设置"))
        self.label_13.setText(_translate("MainWindow", "左右节点"))
        self.source_arg_del.setText(_translate("MainWindow", "移除"))
        self.label_54.setText(_translate("MainWindow", "电压值"))
        self.label_4.setText(_translate("MainWindow", "运行模式设置"))
        self.source_add_list.setText(_translate("MainWindow", "添加"))
        self.label_55.setText(_translate("MainWindow", "模式名称"))
        self.label_58.setText(_translate("MainWindow", "模式信息"))
        self.source_model_apply.setText(_translate("MainWindow", "应用"))
        self.source_model_save.setText(_translate("MainWindow", "保存"))
        self.source_model_del.setText(_translate("MainWindow", "读取"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "电源"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "线路"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "雷电"))
        self.label_52.setText(_translate("MainWindow", "仿真信息"))
        self.label_53.setText(_translate("MainWindow", "项目名称"))
        self.label_64.setText(_translate("MainWindow", "结果标签"))
        self.result_all_tips_rB.setText(_translate("MainWindow", "全选"))
        self.label_56.setText(_translate("MainWindow", "仿真结果"))
        self.result_max_cb.setText(_translate("MainWindow", "最大值"))
        self.result_min_cb.setText(_translate("MainWindow", "最小值"))
        self.result_average_cb.setText(_translate("MainWindow", "平均值"))
        self.result_all_cb.setText(_translate("MainWindow", "全选"))
        self.label_2.setText(_translate("MainWindow", "时间区间"))
        self.label_18.setText(_translate("MainWindow", " 到 "))
        self.label_57.setText(_translate("MainWindow", "结果报告"))
        self.label_71.setText(_translate("MainWindow", "报告内容"))
        self.result_report_pic_cb.setText(_translate("MainWindow", "结果图"))
        self.result_report_table_cb.setText(_translate("MainWindow", "结果表"))
        self.result_report_brief_cb.setText(_translate("MainWindow", "基本信息"))
        self.pushButton_11.setText(_translate("MainWindow", "生成报告"))
        self.pushButton_12.setText(_translate("MainWindow", "上传报告模板"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "结果处理与分析"))
        self.radioButton_7.setText(_translate("MainWindow", "本地模式"))
        self.label_66.setText(_translate("MainWindow", "运行核心数"))
        self.label_65.setText(_translate("MainWindow", "本地运行参数设置"))
        self.radioButton_8.setText(_translate("MainWindow", "网络模式"))
        self.label_67.setText(_translate("MainWindow", "用户名"))
        self.label_68.setText(_translate("MainWindow", "密码"))
        self.label_69.setText(_translate("MainWindow", "服务器地址"))
        self.label_70.setText(_translate("MainWindow", "连接测试"))
        self.pushButton_10.setText(_translate("MainWindow", "点击测试"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "网络设置"))
        self.default_btn.setText(_translate("MainWindow", "恢复初始设置"))
        self.btn_run.setText(_translate("MainWindow", "运行"))
        self.cancel_btn.setText(_translate("MainWindow", "取消"))

