# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Welcom.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WelcomeWindow(object):
    def setupUi(self, WelcomeWindow):
        WelcomeWindow.setObjectName("WelcomeWindow")
        WelcomeWindow.resize(901, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WelcomeWindow.sizePolicy().hasHeightForWidth())
        WelcomeWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(WelcomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ItemLableList = QtWidgets.QVBoxLayout()
        self.ItemLableList.setObjectName("ItemLableList")
        self.label_1 = ItemLabel(self.centralwidget)
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.ItemLableList.addWidget(self.label_1)
        self.label_2 = ItemLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.ItemLableList.addWidget(self.label_2)
        self.label_3 = ItemLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.ItemLableList.addWidget(self.label_3)
        self.label_4 = ItemLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.ItemLableList.addWidget(self.label_4)
        self.label_5 = ItemLabel(self.centralwidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.ItemLableList.addWidget(self.label_5)
        self.label_6 = ItemLabel(self.centralwidget)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.ItemLableList.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.ItemLableList)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.log = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI Light")
        font.setPointSize(48)
        self.log.setFont(font)
        self.log.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.log.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.log.setAutoFillBackground(False)
        self.log.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.log.setTextFormat(QtCore.Qt.PlainText)
        self.log.setAlignment(QtCore.Qt.AlignCenter)
        self.log.setObjectName("log")
        self.verticalLayout_5.addWidget(self.log)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.button_loadADP = QtWidgets.QPushButton(self.widget)
        self.button_loadADP.setGeometry(QtCore.QRect(200, 60, 140, 40))
        self.button_loadADP.setObjectName("button_loadADP")
        self.button_settingATPRun = QtWidgets.QPushButton(self.widget)
        self.button_settingATPRun.setGeometry(QtCore.QRect(200, 120, 140, 40))
        self.button_settingATPRun.setObjectName("button_settingATPRun")
        self.button_help = QtWidgets.QPushButton(self.widget)
        self.button_help.setGeometry(QtCore.QRect(200, 180, 140, 40))
        self.button_help.setObjectName("button_help")
        self.verticalLayout_4.addWidget(self.widget)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 3)
        WelcomeWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(WelcomeWindow)
        self.statusbar.setObjectName("statusbar")
        WelcomeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(WelcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(WelcomeWindow)

    def retranslateUi(self, WelcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        WelcomeWindow.setWindowTitle(_translate("WelcomeWindow", "ATPRase"))
        self.log.setText(_translate("WelcomeWindow", "ATPRase"))
        self.button_loadADP.setText(_translate("WelcomeWindow", "加载ADP"))
        self.button_settingATPRun.setText(_translate("WelcomeWindow", "配置ATP运行环境"))
        self.button_help.setText(_translate("WelcomeWindow", "帮助"))

from ItemLabel import ItemLabel
